## Instructions for the STAC32 Project

You may work on this project alone or in a group of up to 5 people. If you don't have a group to work in, feel free to use Forum 1 of the Discussions to search for colleagues. My suggestion is to find a dataset (see next paragraph) that you like first, and then post in Forum 1 looking for partners to work on that dataset.

Go to the [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday) website and scroll down to the table of Datasets. There is one data set per week for three years, so there is plenty of data to choose from. Use data from 2019 or 2018 if you want - click on the year links between the word Datasets and the (2020) datasets themselves. You can pick a dataset whose subject matter appeals to you, or one that you think lends itself to showing off something that you have learned in this course. To get the data, click on the appropriate thing in the Data column, and scroll down to Get the Data Here. There is also (usually) a Data Dictionary that says what each column of each dataframe (there is sometimes more than one) contains.

Some of the datasets may be more suitable for a project in this course than others. Use your judgement.

For your chosen dataset, think of an interesting question that you can answer using an inference method that you have learned in this course (for example, $t$-test, sign test, analysis of variance, regression), and as far as the data permit, answer that question, using appropriate graphs and checking of assumptions to support your analysis. If the dataset is complicated, I would also be interested in something that makes it easier to understand, such as a map, but I expect you to do some research (citing your sources) to figure out what to do if you take this approach.

Write a report that tells the story of your analysis, including an introduction that describes your chosen dataset, for the benefit of someone who has never seen it before, and states what you are trying to find out. Your report should also have a conclusion that summarizes what you have found. Imagine that you are writing a report that other students in the class will want to read; this is the audience you are aiming for.

As with anything else here, if you use something from outside this course and the description of your dataset, you *must* cite it in such a way that I can find it. Failure to do so is *plagiarism*. (Wouldn't you want to receive credit for your hard work? Then give that credit to others.) In the dataset descriptions, there might be other links that give some other information or background; if you use information from any of these in your report, *cite them*. 

Some of the datasets have a "cleaning script"; you may use this, if your dataset has one, but you should in your report explain what it does. If you prefer, you may do your own data cleaning. 

I don't know any more about these datasets than what is on the website. You will need to answer your own questions and make your own assumptions about the data.

I have no particular preferences about *how* you cite your sources. As long as it is clear where anything from outside this course and the Tidy Tuesday website comes from, I am happy. 
A reminder that by submitting your report, you are certifying that it is the work only of the people named on it.

The grading scheme for this project is the same as for the assignments. The project is due at 11:59pm on the last day of classes (December 7, 2020).
